# Generated by Django 5.1.7 on 2025-07-18 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
