# Generated by Django 5.1.7 on 2025-07-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='accepted', max_length=20),
        ),
    ]
